name: Publish package to npm registry

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    name: build and publish package to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Doing a clean installation of dependencies
        run: npm ci
      - name: build the package with vite
        run: npm run build
      - name: Publish package to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
